### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by maacl** [Vetd-Inc/vetd-app#336]
categories.sql appears to be missing from the migrations_data directory. It is referenced in https://github.com/Vetd-Inc/vetd-app/blob/master/src/clj/com/vetd/app/migrations.clj#L8.

**Comment by celwell** [comment]
Just added some example data.

**Comment by maacl** [comment]
Thanks. Now I get:

`18:41:58.813 [main] ERROR migratus.migration.sql - ERROR: relation "vetd.schema_migrations" does not exist`
